## 1: Import libraries and dataset
### 1.1: Importing libraries¶

In [82]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.2.0'

### 1.2: Importing the dataset

In [83]:
data_true = pd.read_csv('True.csv') #contains news which are true
data_fake = pd.read_csv('Fake.csv') #contains news which are fake
data_train = pd.read_csv('train.csv') # contains mixed news
data_true['class'] = 0 #adding a new column with class 0 indicating not fake news 
data_fake['class'] = 1 #adding a new column with class 1 indicating fake news

### 1.3: Select 'title' and 'class' columns from data_train, data_true and data_ fake for making the final dataset

In [84]:
data_train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [85]:
data_train.columns=['id','title','author','text','class'] # change 'label' to 'class' in columns names
data_train = data_train.loc[:,['title','class']] 
label = data_train['class']
print(label.value_counts())
data_train

1    10413
0    10387
Name: class, dtype: int64


title  class
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...      0
2                      Why the Truth Might Get You Fired      1
3      15 Civilians Killed In Single US Airstrike Hav...      1
4      Iranian woman jailed for fictional unpublished...      1
...                                                  ...    ...
20795  Rapper T.I.: Trump a ’Poster Child For White S...      0
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...      0
20797  Macy’s Is Said to Receive Takeover Approach by...      0
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1
20799                          What Keeps the F-35 Alive      1

[20800 rows x 2 columns]

In [86]:
data_fake = data_fake.loc[:,['title','class']]
data_fake

title  class
0       Donald Trump Sends Out Embarrassing New Year’...      1
1       Drunk Bragging Trump Staffer Started Russian ...      1
2       Sheriff David Clarke Becomes An Internet Joke...      1
3       Trump Is So Obsessed He Even Has Obama’s Name...      1
4       Pope Francis Just Called Out Donald Trump Dur...      1
...                                                  ...    ...
23476  McPain: John McCain Furious That Iran Treated ...      1
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...      1
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...      1
23479  How to Blow $700 Million: Al Jazeera America F...      1
23480  10 U.S. Navy Sailors Held by Iranian Military ...      1

[23481 rows x 2 columns]

In [87]:
data_true = data_true.loc[:,['title','class']]
data_true

title  class
0      As U.S. budget fight looms, Republicans flip t...      0
1      U.S. military to accept transgender recruits o...      0
2      Senior U.S. Republican senator: 'Let Mr. Muell...      0
3      FBI Russia probe helped by Australian diplomat...      0
4      Trump wants Postal Service to charge 'much mor...      0
...                                                  ...    ...
21412  'Fully committed' NATO backs new U.S. approach...      0
21413  LexisNexis withdrew two products from Chinese ...      0
21414  Minsk cultural hub becomes haven from authorities      0
21415  Vatican upbeat on possibility of Pope Francis ...      0
21416  Indonesia to buy $1.14 billion worth of Russia...      0

[21417 rows x 2 columns]

### 1.3: Combine dataframes 'data_true' and 'data_fake' and check if the combined data consists of any null values

In [88]:
data_true_fake = data_true.append(data_fake) # combine data_true with data_fake 
data_true_fake = data_true_fake.reset_index() # resetting index
data_true_fake.dropna() # dropping rows having nan values

index                                              title  class
0          0  As U.S. budget fight looms, Republicans flip t...      0
1          1  U.S. military to accept transgender recruits o...      0
2          2  Senior U.S. Republican senator: 'Let Mr. Muell...      0
3          3  FBI Russia probe helped by Australian diplomat...      0
4          4  Trump wants Postal Service to charge 'much mor...      0
...      ...                                                ...    ...
44893  23476  McPain: John McCain Furious That Iran Treated ...      1
44894  23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...      1
44895  23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...      1
44896  23479  How to Blow $700 Million: Al Jazeera America F...      1
44897  23480  10 U.S. Navy Sailors Held by Iranian Military ...      1

[44898 rows x 3 columns]

In [93]:
data = data_true_fake.append(data_train)
#data.drop(columns='index', axis=1, inplace=True)
data = data.sample(frac=1) # shuffle rows 
data = data.iloc[:,-2:]
data

title  class
23394   CNN Guest’s Face After Trump Flack Blatantly ...      1
40672  ANGRY VETERAN Posts Emotional Viral Video Agai...      1
34927  WOW! WASHED UP LIBERAL CHER Uses Tweet About F...      1
6102   Trump Treasury nominee wants to loosen limits ...      0
1471   Under pressure from Trump, Price resigns as he...      0
...                                                  ...    ...
11327  Russia accuses U.S. of training former Islamic...      0
20314  Germany's Merkel rejects total ban on arms exp...      0
35049  HILLARY SHARES PRO-ILLEGAL MANIFESTO: Plans To...      1
18926  Microcephaly Found in Babies of Zika-Infected ...      0
14840  EU support of Libyan coast guard 'inhuman': U....      0

[65698 rows x 2 columns]

In [94]:
data.reset_index(inplace=True)
data = data.iloc[:,-2:]

In [95]:
data

title  class
0       CNN Guest’s Face After Trump Flack Blatantly ...      1
1      ANGRY VETERAN Posts Emotional Viral Video Agai...      1
2      WOW! WASHED UP LIBERAL CHER Uses Tweet About F...      1
3      Trump Treasury nominee wants to loosen limits ...      0
4      Under pressure from Trump, Price resigns as he...      0
...                                                  ...    ...
65693  Russia accuses U.S. of training former Islamic...      0
65694  Germany's Merkel rejects total ban on arms exp...      0
65695  HILLARY SHARES PRO-ILLEGAL MANIFESTO: Plans To...      1
65696  Microcephaly Found in Babies of Zika-Infected ...      0
65697  EU support of Libyan coast guard 'inhuman': U....      0

[65698 rows x 2 columns]

In [96]:
data.shape

(65698, 2)

In [98]:
data['title'][4]

'Under pressure from Trump, Price resigns as health secretary over private plane uproar'

### 1.4: Preparing X and y set for training and testing

In [99]:
X = data[['title']]
X

title
0       CNN Guest’s Face After Trump Flack Blatantly ...
1      ANGRY VETERAN Posts Emotional Viral Video Agai...
2      WOW! WASHED UP LIBERAL CHER Uses Tweet About F...
3      Trump Treasury nominee wants to loosen limits ...
4      Under pressure from Trump, Price resigns as he...
...                                                  ...
65693  Russia accuses U.S. of training former Islamic...
65694  Germany's Merkel rejects total ban on arms exp...
65695  HILLARY SHARES PRO-ILLEGAL MANIFESTO: Plans To...
65696  Microcephaly Found in Babies of Zika-Infected ...
65697  EU support of Libyan coast guard 'inhuman': U....

[65698 rows x 1 columns]

In [100]:
y=data['class']
y

0        1
1        1
2        1
3        0
4        0
        ..
65693    0
65694    0
65695    1
65696    0
65697    0
Name: class, Length: 65698, dtype: int64

In [101]:
y.value_counts()

1    33894
0    31804
Name: class, dtype: int64

In [102]:
print(X.shape)
print(y.shape)

(65698, 1)
(65698,)


## 2: Preprocess the data for training and create the LSTM architecture

### 2.1: Import libraries from tensorflow for preprocessing and LSTM architecture

In [103]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [104]:
vocab_size = 10000 #vocabulary size

In [105]:
temp = X.copy()
temp['title'][0]

' CNN Guest’s Face After Trump Flack Blatantly Lies About Obama Golfing Is All Of Us Right Now (VIDEO)'

In [106]:
content = temp.reset_index()
content

index                                              title
0          0   CNN Guest’s Face After Trump Flack Blatantly ...
1          1  ANGRY VETERAN Posts Emotional Viral Video Agai...
2          2  WOW! WASHED UP LIBERAL CHER Uses Tweet About F...
3          3  Trump Treasury nominee wants to loosen limits ...
4          4  Under pressure from Trump, Price resigns as he...
...      ...                                                ...
65693  65693  Russia accuses U.S. of training former Islamic...
65694  65694  Germany's Merkel rejects total ban on arms exp...
65695  65695  HILLARY SHARES PRO-ILLEGAL MANIFESTO: Plans To...
65696  65696  Microcephaly Found in Babies of Zika-Infected ...
65697  65697  EU support of Libyan coast guard 'inhuman': U....

[65698 rows x 2 columns]

In [107]:
content['title'][1]

'ANGRY VETERAN Posts Emotional Viral Video Against Flag Burning: “What’s happening is sickening” [Video]'

### 2.2: Preprocess data

In [108]:
import nltk
import re
from nltk.corpus import stopwords

In [109]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [110]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
complete=[]

for i in range(0,len(content)):
    title = re.sub('[^a-zA-Z]', ' ', str(content['title'][i])) # remove all symbols/numbers 
    title = title.lower() # lowercase
    title = title.split()
    title = [ps.stem(word) for word in title if not word in stopwords.words('english')] # remove stopwords and perform stemming
    title = ' '.join(title)
    complete.append(title)

In [115]:
print(len(complete))
complete[:10]

65698


['cnn guest face trump flack blatantli lie obama golf us right video',
 'angri veteran post emot viral video flag burn happen sicken video',
 'wow wash liber cher use tweet franc terror attack remind follow award',
 'trump treasuri nomine want loosen limit volcker rule document',
 'pressur trump price resign health secretari privat plane uproar',
 'london get n f l game bad team new york time',
 'pot decrimin save philadelphia million',
 'hillari clinton white voter melt away',
 'nan',
 'u presidenti campaign discuss fed polici meet offici']

### 2.3: One-hot representation

In [112]:
one_hot_encoded = [one_hot(titles, vocab_size) for titles in complete]

In [113]:
one_hot_encoded

[[7998, 4476, 3549, 6879, 4899, 1400, 2728, 1445, 556, 1092, 9894, 5480],
 [9419, 6437, 726, 468, 5598, 5480, 1758, 679, 285, 4580, 5480],
 [1969, 6041, 9370, 1834, 8270, 3217, 7358, 3625, 5268, 4237, 5108, 7494],
 [6879, 9430, 6147, 2028, 6458, 5334, 8383, 3504, 596],
 [8442, 6879, 7969, 7896, 2628, 9233, 9909, 3598, 2919],
 [6633, 6046, 9628, 2708, 4815, 1826, 4818, 3326, 6730, 8365, 94],
 [2457, 4060, 6273, 4101, 7916],
 [1675, 1709, 580, 8666, 1665, 5484],
 [4107],
 [9576, 2189, 2300, 6470, 6644, 5779, 1419, 6495],
 [3480, 2028, 5490, 8856, 1078, 2367, 9092, 409],
 [5677, 133, 876, 3135],
 [9384, 5206, 6046, 6769, 9372, 9194, 9378, 930, 4818, 6279],
 [3849, 7244, 7742, 9807, 7916, 7746, 8601, 8666, 6915, 4295],
 [4785, 5493, 8093, 7995, 8393, 423, 2271, 9556, 6730, 8365, 94],
 [1445, 5413, 94, 5677, 1709],
 [2707, 790, 4137, 8222, 9584, 2656, 9593, 2742, 177, 6539, 4893, 7247],
 [8137,
  3310,
  158,
  9293,
  9548,
  4448,
  5925,
  3310,
  1811,
  6125,
  4831,
  7150,
  1709,
  

### 2.4 Word embedding representation

In [116]:
sentence_max_length = 25
embedded_complete = pad_sequences(one_hot_encoded, maxlen = sentence_max_length, padding='pre') # padding the one-hot encoded data 

In [117]:
embedded_complete

array([[   0,    0,    0, ..., 1092, 9894, 5480],
       [   0,    0,    0, ...,  285, 4580, 5480],
       [   0,    0,    0, ..., 4237, 5108, 7494],
       ...,
       [   0,    0,    0, ..., 6701, 7746, 5806],
       [   0,    0,    0, ..., 6730, 8365,   94],
       [   0,    0,    0, ..., 9628, 9894, 4820]])

In [118]:
embedded_complete[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 7998, 4476, 3549, 6879, 4899, 1400, 2728, 1445,  556,
       1092, 9894, 5480])

### 2.5: Creating the LSTM architecture

In [119]:
embedding_features = 50
model = Sequential()
model.add(Embedding(vocab_size, embedding_features, input_length = sentence_max_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.3))
#model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [120]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 50)            500000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               120800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 621,001
Trainable params: 621,001
Non-trainable params: 0
_________________________________________________________________


In [121]:
X_main = np.array(embedded_complete)
y_main = np.array(y)

In [122]:
print(X_main.shape)
X_main

(65698, 25)


array([[   0,    0,    0, ..., 1092, 9894, 5480],
       [   0,    0,    0, ...,  285, 4580, 5480],
       [   0,    0,    0, ..., 4237, 5108, 7494],
       ...,
       [   0,    0,    0, ..., 6701, 7746, 5806],
       [   0,    0,    0, ..., 6730, 8365,   94],
       [   0,    0,    0, ..., 9628, 9894, 4820]])

In [123]:
print(y_main.shape)
y_main

(65698,)


array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

## 3: Training the model 
### 3.1: Splitting the data into train and test set 

In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_main, y_main, test_size=0.3)

### 3.2: Training

In [125]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, batch_size=64)

Epoch 1/20
719/719 [==============================] - 49s 68ms/step - loss: 0.2652 - accuracy: 0.8877 - val_loss: 0.1943 - val_accuracy: 0.9241
Epoch 2/20
719/719 [==============================] - 50s 69ms/step - loss: 0.1516 - accuracy: 0.9424 - val_loss: 0.1876 - val_accuracy: 0.9266
Epoch 3/20
719/719 [==============================] - 55s 77ms/step - loss: 0.1143 - accuracy: 0.9575 - val_loss: 0.2014 - val_accuracy: 0.9232
Epoch 4/20
719/719 [==============================] - 53s 74ms/step - loss: 0.0872 - accuracy: 0.9690 - val_loss: 0.2261 - val_accuracy: 0.9204
Epoch 5/20
719/719 [==============================] - 52s 72ms/step - loss: 0.0669 - accuracy: 0.9765 - val_loss: 0.2589 - val_accuracy: 0.9190
Epoch 6/20
719/719 [==============================] - 53s 74ms/step - loss: 0.0489 - accuracy: 0.9826 - val_loss: 0.3272 - val_accuracy: 0.9184
Epoch 7/20
719/719 [==============================] - 55s 77ms/step - loss: 0.0374 - accuracy: 0.9864 - val_loss: 0.3619 - val_accuracy:

## 4: Results
### 4.1: predicting the results on test set

In [131]:
X_test.shape

(19710, 25)

In [132]:
y_pred = model.predict_classes(X_test)

### 4.2: Analyzing the results 

In [133]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_pred, y_test)
cm

array([[8607,  797],
       [ 920, 9386]], dtype=int64)

In [134]:
accuracy = accuracy_score(y_pred, y_test)
print(accuracy*100)

91.2886859462202


In [135]:
cr = classification_report(y_pred, y_test)
print(cr)

              precision    recall  f1-score   support

           0       0.90      0.92      0.91      9404
           1       0.92      0.91      0.92     10306

    accuracy                           0.91     19710
   macro avg       0.91      0.91      0.91     19710
weighted avg       0.91      0.91      0.91     19710



### Result: 91.2% accuracy is achieved by the model, which is reasonably good. 
### We can also see Precision is 0.91 which is very nice as with high precision we reduce the chances of predicting fake news as authentic news

### 4.3: Predicting result for single sentence

In [136]:
sent = 'I think president of united states in indian in origin, indians should vote him'
title = re.sub('[^a-zA-Z]', ' ', sent)
title = title.lower()
title = title.split()
title = [ps.stem(word) for word in title if not word in stopwords.words('english')]
title = ' '.join(title)
title

'think presid unit state indian origin indian vote'

In [137]:
one_hot_sent = [one_hot(title, vocab_size)]

In [138]:
one_hot_sent

[[7222, 1089, 4233, 3310, 9989, 9302, 9989, 5919]]

In [139]:
sent_pad = pad_sequences(one_hot_sent, padding='pre', maxlen=sentence_max_length)

In [140]:
sent_pad

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0, 7222, 1089, 4233, 3310, 9989,
        9302, 9989, 5919]])

In [141]:
t = model.predict_classes(sent_pad)
int(t[0])

1

### 4.4: Function to predict fake or not for a single sentence

In [142]:
def fake_or_not(sentence):
    sent = sentence
    title = re.sub('[^a-zA-Z]', ' ', sent)
    title = title.lower()
    title = title.split()
    title = [ps.stem(word) for word in title if not word in stopwords.words('english')]
    title = ' '.join(title)
    one_hot_sent = [one_hot(title, vocab_size)]
    sent_pad = pad_sequences(one_hot_sent, padding='pre', maxlen=sentence_max_length)
    prediction = int(model.predict_classes(sent_pad))
    if prediction == 1:
        print("Fake!!")
    else:
        print("Not Fake!!")

In [143]:
fake_or_not(sent)

Fake!!


In [146]:
t1 = 'trump treasuri nomine want loosen limit volcker rule document'
fake_or_not(t1)

Not Fake!!


### 4.5: Save the model as .pkl file

In [ ]:
pickle.dump(model, open('model.pkl','wb'))